# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.16
  working_directory: ~/project/remote-data

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn build

      - persist_to_workspace:
          root: ~/project
          paths:
            - remote-data

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn test

  publish:
    <<: *defaults

    steps:
      - *attach_workspace
      - checkout

      - run: yarn config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: yarn release-ci

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
