# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.16
  working_directory: ~/project/functional-types

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn build

      - persist_to_workspace:
          root: ~/project
          paths:
            - functional-types

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: yarn test

  github_publish:
    <<: *defaults

    steps:
      - *attach_workspace
      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc

      - run: yarn release-github

  npm_publish:
    <<: *defaults

    steps:
      - *attach_workspace
      - checkout

      - run: yarn release-npm

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - github_publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - npm_publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.\d+\.\d+\.\d+\.$/
            branches:
              ignore: /.*/
